# Generated by Django 4.2.24 on 2026-01-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('pool', models.CharField(blank=True, max_length=50)),
                ('seuil_eligibilite', models.FloatField(default=12.5)),
                ('pourcentage_modules_communs', models.FloatField(default=0.8)),
                ('pourcentage_modules_specifiques', models.FloatField(default=0.2)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=160)),
                ('semestre', models.CharField(max_length=10)),
                ('type_module', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, unique=True)),
                ('pays', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NOT_STARTED', 'Non démarrée'), ('ACTIVE', 'En cours'), ('CLOSED', 'Clôturée')], default='NOT_STARTED', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
