# Generated by Django 4.2.24 on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partenaire",
            name="contact_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="partenaire",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="partenaire",
            name="ville",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
