# Generated by Django 4.2.24 on 2026-01-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobility', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(choices=[('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé')], max_length=10)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('lettre_acceptation', models.FileField(blank=True, null=True, upload_to='lettres/')),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobility.affectation')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partenaire')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobility.student')),
            ],
        ),
    ]
