# Generated by Django 4.2.24 on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerdecision",
            name="decision_partenaire",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="partnerdecision",
            name="lettre_reponse",
            field=models.FileField(blank=True, null=True, upload_to="lettres/"),
        ),
    ]
