# Generated by Django 4.2.24 on 2026-01-08 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere_partenaire', models.CharField(max_length=120)),
                ('annee', models.PositiveIntegerField()),
                ('type_mobilite', models.CharField(choices=[('EXCHANGE', 'Échange'), ('DOUBLE_DEGREE', 'Double diplôme')], max_length=20)),
                ('nombre_places', models.PositiveIntegerField(default=0)),
                ('flechee', models.BooleanField(default=False)),
                ('filiere_ensias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filiere')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='core.partenaire')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cne', models.CharField(max_length=20, unique=True)),
                ('code_apogee', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('redoublement_a1', models.BooleanField(default=False)),
                ('blame', models.BooleanField(default=False)),
                ('moyenne_a1', models.FloatField(blank=True, null=True)),
                ('moyenne_s3', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ELIGIBLE', 'Éligible'), ('NOT_ELIGIBLE', 'Non éligible'), ('DESIDERATA_SUBMITTED', 'Desiderata soumis'), ('ASSIGNED', 'Affecté'), ('INTERVIEW', 'Entretien'), ('SENT_TO_PARTNER', 'Envoyé partenaire'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé')], default='DRAFT', max_length=30)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_selection', models.FloatField(blank=True, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('passe_attente', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection_result', to='mobility.student')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateTimeField()),
                ('motivation', models.TextField(blank=True)),
                ('capacite_financiere', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('ACCEPT', 'Valider'), ('REFUSE', 'Refuser'), ('DESISTE', 'Désistement')], max_length=10, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entretien', to='mobility.student')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[('CONVENTION', 'Convention'), ('RELEVES', 'Relevés'), ('CV', 'CV'), ('LETTRE_MOTIV', 'Lettre de motivation'), ('AUTRE', 'Autre')], max_length=30)),
                ('fichier', models.FileField(upload_to='docs/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('statut_validation', models.CharField(choices=[('PENDING', 'En attente'), ('VALID', 'Validé'), ('INVALID', 'Refusé')], default='PENDING', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mobility.student')),
            ],
        ),
        migrations.CreateModel(
            name='Desiderata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALID', 'Validé'), ('INVALID', 'Refusé'), ('RECTIFICATION', 'En rectification')], default='DRAFT', max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desiderata', to='mobility.student')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('DEFINITIVE', 'Définitive'), ('DESISTE', 'Désisté')], default='PROVISOIRE', max_length=20)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobility.alignmentplace')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affectation', to='mobility.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_univ', models.CharField(max_length=9)),
                ('note', models.FloatField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mobility.student')),
            ],
            options={
                'unique_together': {('student', 'module', 'annee_univ')},
            },
        ),
        migrations.CreateModel(
            name='DesiderataChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('desiderata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mobility.desiderata')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobility.alignmentplace')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('desiderata', 'rank')},
            },
        ),
    ]
