# Generated by Django 4.2.24 on 2026-01-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mobility", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmentplace",
            name="open_to_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="desiderata",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="desiderata",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_desiderata",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="affectation",
            name="decision_partenaire",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="affectation",
            name="lettre_reponse",
            field=models.FileField(blank=True, null=True, upload_to="lettres/"),
        ),
        migrations.AddField(
            model_name="documentadministratif",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentadministratif",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
